# - Try to find rf4ce support
# Once done this will define
#  RF4CE_FOUND - System has rf4ce support
#  RF4CE_INCLUDE_DIRS - The rf4ce include directories
#  RF4CE_LIBRARIES - The libraries needed to use rf4ce
#
# Copyright (C) 2017 Metrological B.V.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1.  Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
# 2.  Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND ITS CONTRIBUTORS ``AS
# IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR ITS
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NRF4CEIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

find_package(PkgConfig)
pkg_check_modules(PC_RF4CE rf4ce)

if (PC_RF4CE_FOUND)
    find_library(RF4CE_LIBRARY NAMES qorvorf4ce)

    set(RF4CE_CFLAGS ${PC_RF4CE_CFLAGS})
    set(RF4CE_FOUND ${PC_RF4CE_FOUND})
    set(RF4CE_DEFINITIONS ${PC_RF4CE_CFLAGS_OTHER})
    set(RF4CE_NAMES ${PC_RF4CE_LIBRARIES})
    set(RF4CE_INCLUDE_DIRS ${PC_RF4CE_INCLUDE_DIRS})

    foreach (_library ${RF4CE_NAMES})
        find_library(RF4CE_LIBRARIES_${_library} ${_library}
                HINTS ${PC_RF4CE_LIBDIR} ${PC_RF4CE_LIBRARY_DIRS}
                )
        set(RF4CE_LIBRARIES ${RF4CE_LIBRARIES} ${RF4CE_LIBRARIES_${_library}})
    endforeach ()
else()
    # TODO: This needs to be removed ASAP, we should always rely on pkg-config
    find_path(LIBGP_INCLUDE_DIR gpVersion.h
        PATHS usr/include/
        PATH_SUFFIXES gprf4ce
        )

    find_library(RF4CE_LIBRARY NAMES RefTarget_ZRC_MSO_GP712_FEM_RDK_WorldBox)

    set(RF4CE_DEFINITIONS
            -DGP_CHANGELIST=70269
            -DGP_COMPONENT_ID_APP=1
            -DGP_COMPONENT_ID_ASSERT=29
            -DGP_COMPONENT_ID_BASECOMPS=35
            -DGP_COMPONENT_ID_BSP=8
            -DGP_COMPONENT_ID_ENCRYPTION=124
            -DGP_COMPONENT_ID_FA=26
            -DGP_COMPONENT_ID_GPHAL=7
            -DGP_COMPONENT_ID_HALLINUX=6
            -DGP_COMPONENT_ID_LOG=11
            -DGP_COMPONENT_ID_MACCORE=109
            -DGP_COMPONENT_ID_MACDISPATCHER=114
            -DGP_COMPONENT_ID_NVM=32
            -DGP_COMPONENT_ID_PAD=126
            -DGP_COMPONENT_ID_PD=104
            -DGP_COMPONENT_ID_POOLMEM=106
            -DGP_COMPONENT_ID_RANDOM=108
            -DGP_COMPONENT_ID_RESET=33
            -DGP_COMPONENT_ID_RF4CE=25
            -DGP_COMPONENT_ID_RF4CEBINDAUTO=45
            -DGP_COMPONENT_ID_RF4CEDISPATCHER=40
            -DGP_COMPONENT_ID_RF4CEUSERCONTROL=41
            -DGP_COMPONENT_ID_RXARBITER=2
            -DGP_COMPONENT_ID_SCHED=9
            -DGP_COMPONENT_ID_STAT=22
            -DGP_COMPONENT_ID_UTILS=4
            -DGP_COMPONENT_ID_VERSION=129
            -DGP_COMPONENT_ID_WMRK=51
            -DGP_COMP_GPHAL_ES_ABS_EVENT
            -DGP_COMP_GPHAL_ES_REL_EVENT
            -DGP_DIVERSITY_GPHAL_EXTERN
            -DGP_DIVERSITY_NR_OF_STACKS=1
            -DGP_HAL_ES_NUMBER_OF_ABS_EVENT_RX_ARBITER=2
            -DGP_MACCORE_DIVERSITY_SCAN_ACTIVE_ORIGINATOR
            -DGP_MACCORE_DIVERSITY_SCAN_ACTIVE_RECIPIENT
            -DGP_MACCORE_DIVERSITY_SCAN_ED_ORIGINATOR
            -DGP_MACCORE_DIVERSITY_SCAN_ORIGINATOR
            -DGP_MACCORE_DIVERSITY_SCAN_ORPHAN_ORIGINATOR
            -DGP_MACCORE_DIVERSITY_SCAN_ORPHAN_RECIPIENT
            -DGP_MACCORE_DIVERSITY_SCAN_RECIPIENT
            -DGP_NVM_NBR_OF_SECTIONS=4
            -DGP_POOLMEM_CHUNK_AMOUNT1=4
            -DGP_POOLMEM_CHUNK_AMOUNT2=5
            -DGP_POOLMEM_CHUNK_AMOUNT3=5
            -DGP_POOLMEM_CHUNK_SIZE1=30
            -DGP_POOLMEM_CHUNK_SIZE2=50
            -DGP_POOLMEM_CHUNK_SIZE3=100
            -DGP_RF4CE_BIND_AUTO_USER_STRING=UPC_Horizon
            -DGP_RF4CE_DIVERSITY_AUTO_DISCOVERY
            -DGP_RF4CE_MAX_DISCOVERY_PROFILEID_LIST_SIZE=7
            -DGP_RF4CE_MAX_NODE_DESCRIPTOR_LIST_SIZE=16
            -DGP_RF4CE_NWKC_MAX_PAIRING_TABLE_ENTRIES=6
            -DGP_RF4CE_NWKC_VENDOR_IDENTIFIER=0x0003
            -DGP_RF4CE_NWKC_VENDOR_STRING=SUMSUG
            -DGP_RF4CE_USER_CONTROL_IND_MAX_PENDING_KEYS=1
            -DGP_RF4CE_USER_CONTROL_PROFILE_ID_LIST=gpRf4ce_ProfileIdZrc
            -DGP_RF4CE_USER_CONTROL_REQ_MAX_PENDING_KEYS=0
            -DGP_SCHED_DEFAULT_GOTOSLEEP_THRES=1
            -DGP_SCHED_EVENT_LIST_SIZE=30
            -DGP_SCHED_FREE_CPU_TIME=5000
            -DGP_VERSIONINFO_APP=RemoteControl
            -DGP_VERSIONINFO_BASE_COMPS=2,4,5,2
            -DGP_VERSIONINFO_CONFIG=/
            -DGP_VERSIONINFO_DATE=2015-09-11
            -DGP_VERSIONINFO_GLOBAL_VERSION=2,4,5,2
            -DGP_VERSIONINFO_HOST=UNKNOWN
            -DGP_VERSIONINFO_PROJECT=METROLOGICAL
            -DGP_VERSIONINFO_RACE_VERSION=1,3,2,1
            -DGP_VERSIONINFO_USER=UNKNOWN@UNKNOWN)

    set(RF4CE_INCLUDE_DIRS ${LIBGP_INCLUDE_DIR})
    set(RF4CE_LIBRARIES ${RF4CE_LIBRARY})
endif()

include(FindPackageHandleStandardArgs)

if(EXISTS ${RF4CE_LIBRARY} AND NOT TARGET RF4CE::RF4CE)
    add_library(RF4CE::RF4CE UNKNOWN IMPORTED)
    set_target_properties(RF4CE::RF4CE PROPERTIES
            IMPORTED_LOCATION "${RF4CE_LIBRARY}"
            IMPORTED_LINK_INTERFACE_LANGUAGES "C"
            INTERFACE_LINK_LIBRARIES "${RF4CE_LIBRARIES}"
            INTERFACE_COMPILE_OPTIONS "${RF4CE_DEFINITIONS}"
            INTERFACE_INCLUDE_DIRECTORIES "${RF4CE_INCLUDE_DIRS}"
            )
endif()


find_package_handle_standard_args(RF4CE DEFAULT_MSG RF4CE_LIBRARIES RF4CE_INCLUDE_DIRS)

mark_as_advanced(RF4CE_FOUND RF4CE_INCLUDE_DIRS RF4CE_LIBRARIES)
