#ifndef OPENPLUGIN_DEVICEIDENTIFICATION_MODULE_H
#define OPENPLUGIN_DEVICEIDENTIFICATION_MODULE_H

#ifndef MODULE_NAME
#define MODULE_NAME Plugin_DeviceInfo
#endif

#include <plugins/plugins.h>

#undef EXTERNAL
#define EXTERNAL

#endif // OPENPLUGIN_DEVICEIDENTIFICATION_MODULE_H
