file(GLOB PLUGIN_INCLUDES *.h)

add_library(${MODULE_NAME} SHARED ${PLUGIN_SOURCES} ${PLUGIN_INCLUDES})
target_compile_definitions(${MODULE_NAME} PRIVATE ${PLUGIN_DEFINITIONS})
target_include_directories(${MODULE_NAME} PRIVATE ${PLUGIN_DEPENDENCIES_INCLUDE_DIRS})
target_link_libraries(${MODULE_NAME} ${CMAKE_THREAD_LIBS_INIT} ${CMAKE_DL_LIBS} ${PLUGINS_LIBRARIES} ${PLUGIN_DEPENDENCIES})
set_target_properties(${MODULE_NAME} PROPERTIES OUTPUT_NAME ${MODULE_NAME})

install(
    TARGETS ${MODULE_NAME}
    DESTINATION ${CMAKE_INSTALL_PREFIX}/lib/${NAMESPACE}/plugins
    COMPONENT ${MODULE_NAME})
