name: Build ThunderNanoServices on Linux

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: ["R4_4"]
  pull_request:
    branches: ["R4_4"]

jobs:
  Thunder:
    uses: rdkcentral/Thunder/.github/workflows/Linux build template.yml@R4_4

  ThunderInterfaces:
    needs: Thunder
    uses: rdkcentral/ThunderInterfaces/.github/workflows/Linux build template.yml@R4_4

  ThunderNanoServices:
    needs: ThunderInterfaces
    uses: ./.github/workflows/Linux build template.yml
